apiVersion: v1 
kind: Pod 
metadata: 
    name: dind
    labels: {}
spec:
    activeDeadlineSeconds: 3600           # maximum TTL for pod
    containers: 
      - name: docker-cmds
        image: vladpbr/images-portal-grpc-server:1.0
        ports:
        - containerPort: 7777             # grpc server
          protocol: TCP
        - containerPort: 2375             # docker daemon
          protool: TCP
        resources: 
            requests: 
                cpu: 10m 
                memory: 256Mi 
        env: 
          - name: DOCKER_HOST 
            value: "tcp://localhost:2375" # docker daemon
          - name: DOCKER_API_VERSION
            value: "1.24"                 # match server API version
        securityContext: 
            privileged: true              # docker-in-docker must run as a privileged container
        volumeMounts: 
          - name: docker-graph-storage    # empty placeholder directory for docker
            mountPath: /var/lib/docker
    volumes: 
      - name: docker-graph-storage        # empty placeholder directory for docker
        emptyDir: {}