// Code generated by protoc-gen-go. DO NOT EDIT.
// source: docker/docker.proto

package docker

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type S3Object struct {
	S3Key                string   `protobuf:"bytes,1,opt,name=s3_key,json=s3Key,proto3" json:"s3_key,omitempty"`
	S3Bucket             string   `protobuf:"bytes,2,opt,name=s3_bucket,json=s3Bucket,proto3" json:"s3_bucket,omitempty"`
	S3Accesskey          string   `protobuf:"bytes,3,opt,name=s3_accesskey,json=s3Accesskey,proto3" json:"s3_accesskey,omitempty"`
	S3Secretkey          string   `protobuf:"bytes,4,opt,name=s3_secretkey,json=s3Secretkey,proto3" json:"s3_secretkey,omitempty"`
	S3Endpoint           string   `protobuf:"bytes,5,opt,name=s3_endpoint,json=s3Endpoint,proto3" json:"s3_endpoint,omitempty"`
	S3Region             string   `protobuf:"bytes,6,opt,name=s3_region,json=s3Region,proto3" json:"s3_region,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S3Object) Reset()         { *m = S3Object{} }
func (m *S3Object) String() string { return proto.CompactTextString(m) }
func (*S3Object) ProtoMessage()    {}
func (*S3Object) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f56455402527961, []int{0}
}

func (m *S3Object) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S3Object.Unmarshal(m, b)
}
func (m *S3Object) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S3Object.Marshal(b, m, deterministic)
}
func (m *S3Object) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S3Object.Merge(m, src)
}
func (m *S3Object) XXX_Size() int {
	return xxx_messageInfo_S3Object.Size(m)
}
func (m *S3Object) XXX_DiscardUnknown() {
	xxx_messageInfo_S3Object.DiscardUnknown(m)
}

var xxx_messageInfo_S3Object proto.InternalMessageInfo

func (m *S3Object) GetS3Key() string {
	if m != nil {
		return m.S3Key
	}
	return ""
}

func (m *S3Object) GetS3Bucket() string {
	if m != nil {
		return m.S3Bucket
	}
	return ""
}

func (m *S3Object) GetS3Accesskey() string {
	if m != nil {
		return m.S3Accesskey
	}
	return ""
}

func (m *S3Object) GetS3Secretkey() string {
	if m != nil {
		return m.S3Secretkey
	}
	return ""
}

func (m *S3Object) GetS3Endpoint() string {
	if m != nil {
		return m.S3Endpoint
	}
	return ""
}

func (m *S3Object) GetS3Region() string {
	if m != nil {
		return m.S3Region
	}
	return ""
}

type Image struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f56455402527961, []int{1}
}

func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (m *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(m, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ImagesList struct {
	Images               []*Image `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImagesList) Reset()         { *m = ImagesList{} }
func (m *ImagesList) String() string { return proto.CompactTextString(m) }
func (*ImagesList) ProtoMessage()    {}
func (*ImagesList) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f56455402527961, []int{2}
}

func (m *ImagesList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImagesList.Unmarshal(m, b)
}
func (m *ImagesList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImagesList.Marshal(b, m, deterministic)
}
func (m *ImagesList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImagesList.Merge(m, src)
}
func (m *ImagesList) XXX_Size() int {
	return xxx_messageInfo_ImagesList.Size(m)
}
func (m *ImagesList) XXX_DiscardUnknown() {
	xxx_messageInfo_ImagesList.DiscardUnknown(m)
}

var xxx_messageInfo_ImagesList proto.InternalMessageInfo

func (m *ImagesList) GetImages() []*Image {
	if m != nil {
		return m.Images
	}
	return nil
}

type TagImage struct {
	OldImage             *Image   `protobuf:"bytes,1,opt,name=old_image,json=oldImage,proto3" json:"old_image,omitempty"`
	NewImage             *Image   `protobuf:"bytes,2,opt,name=new_image,json=newImage,proto3" json:"new_image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TagImage) Reset()         { *m = TagImage{} }
func (m *TagImage) String() string { return proto.CompactTextString(m) }
func (*TagImage) ProtoMessage()    {}
func (*TagImage) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f56455402527961, []int{3}
}

func (m *TagImage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TagImage.Unmarshal(m, b)
}
func (m *TagImage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TagImage.Marshal(b, m, deterministic)
}
func (m *TagImage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TagImage.Merge(m, src)
}
func (m *TagImage) XXX_Size() int {
	return xxx_messageInfo_TagImage.Size(m)
}
func (m *TagImage) XXX_DiscardUnknown() {
	xxx_messageInfo_TagImage.DiscardUnknown(m)
}

var xxx_messageInfo_TagImage proto.InternalMessageInfo

func (m *TagImage) GetOldImage() *Image {
	if m != nil {
		return m.OldImage
	}
	return nil
}

func (m *TagImage) GetNewImage() *Image {
	if m != nil {
		return m.NewImage
	}
	return nil
}

type TagImagesList struct {
	Images               []*TagImage `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TagImagesList) Reset()         { *m = TagImagesList{} }
func (m *TagImagesList) String() string { return proto.CompactTextString(m) }
func (*TagImagesList) ProtoMessage()    {}
func (*TagImagesList) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f56455402527961, []int{4}
}

func (m *TagImagesList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TagImagesList.Unmarshal(m, b)
}
func (m *TagImagesList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TagImagesList.Marshal(b, m, deterministic)
}
func (m *TagImagesList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TagImagesList.Merge(m, src)
}
func (m *TagImagesList) XXX_Size() int {
	return xxx_messageInfo_TagImagesList.Size(m)
}
func (m *TagImagesList) XXX_DiscardUnknown() {
	xxx_messageInfo_TagImagesList.DiscardUnknown(m)
}

var xxx_messageInfo_TagImagesList proto.InternalMessageInfo

func (m *TagImagesList) GetImages() []*TagImage {
	if m != nil {
		return m.Images
	}
	return nil
}

type TagAndPushObject struct {
	TagImages            *TagImagesList `protobuf:"bytes,1,opt,name=tag_images,json=tagImages,proto3" json:"tag_images,omitempty"`
	AuthConfig           *AuthConfig    `protobuf:"bytes,2,opt,name=auth_config,json=authConfig,proto3" json:"auth_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *TagAndPushObject) Reset()         { *m = TagAndPushObject{} }
func (m *TagAndPushObject) String() string { return proto.CompactTextString(m) }
func (*TagAndPushObject) ProtoMessage()    {}
func (*TagAndPushObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f56455402527961, []int{5}
}

func (m *TagAndPushObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TagAndPushObject.Unmarshal(m, b)
}
func (m *TagAndPushObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TagAndPushObject.Marshal(b, m, deterministic)
}
func (m *TagAndPushObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TagAndPushObject.Merge(m, src)
}
func (m *TagAndPushObject) XXX_Size() int {
	return xxx_messageInfo_TagAndPushObject.Size(m)
}
func (m *TagAndPushObject) XXX_DiscardUnknown() {
	xxx_messageInfo_TagAndPushObject.DiscardUnknown(m)
}

var xxx_messageInfo_TagAndPushObject proto.InternalMessageInfo

func (m *TagAndPushObject) GetTagImages() *TagImagesList {
	if m != nil {
		return m.TagImages
	}
	return nil
}

func (m *TagAndPushObject) GetAuthConfig() *AuthConfig {
	if m != nil {
		return m.AuthConfig
	}
	return nil
}

type AuthConfig struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthConfig) Reset()         { *m = AuthConfig{} }
func (m *AuthConfig) String() string { return proto.CompactTextString(m) }
func (*AuthConfig) ProtoMessage()    {}
func (*AuthConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f56455402527961, []int{6}
}

func (m *AuthConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthConfig.Unmarshal(m, b)
}
func (m *AuthConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthConfig.Marshal(b, m, deterministic)
}
func (m *AuthConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthConfig.Merge(m, src)
}
func (m *AuthConfig) XXX_Size() int {
	return xxx_messageInfo_AuthConfig.Size(m)
}
func (m *AuthConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthConfig.DiscardUnknown(m)
}

var xxx_messageInfo_AuthConfig proto.InternalMessageInfo

func (m *AuthConfig) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AuthConfig) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Message struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f56455402527961, []int{7}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*S3Object)(nil), "docker.S3Object")
	proto.RegisterType((*Image)(nil), "docker.Image")
	proto.RegisterType((*ImagesList)(nil), "docker.ImagesList")
	proto.RegisterType((*TagImage)(nil), "docker.TagImage")
	proto.RegisterType((*TagImagesList)(nil), "docker.TagImagesList")
	proto.RegisterType((*TagAndPushObject)(nil), "docker.TagAndPushObject")
	proto.RegisterType((*AuthConfig)(nil), "docker.AuthConfig")
	proto.RegisterType((*Message)(nil), "docker.Message")
}

func init() { proto.RegisterFile("docker/docker.proto", fileDescriptor_7f56455402527961) }

var fileDescriptor_7f56455402527961 = []byte{
	// 434 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x6d, 0xda, 0xc4, 0x75, 0x26, 0x54, 0x54, 0x8b, 0x2a, 0x59, 0xe9, 0x81, 0xb2, 0x08, 0x29,
	0xe2, 0x10, 0xa4, 0x2e, 0x97, 0x1e, 0x03, 0xe5, 0x80, 0x28, 0x02, 0xb9, 0xbd, 0x5b, 0x1b, 0x7b,
	0x70, 0x4c, 0x9a, 0xdd, 0xc8, 0xb3, 0x56, 0xd4, 0x03, 0x7f, 0x8e, 0x5f, 0x86, 0x3c, 0xde, 0x75,
	0x3f, 0xe8, 0xc9, 0xf3, 0xf6, 0xbd, 0x99, 0x79, 0x7e, 0x5e, 0xc3, 0xab, 0xc2, 0xe6, 0x6b, 0xac,
	0x3f, 0x74, 0x8f, 0xf9, 0xb6, 0xb6, 0xce, 0x8a, 0xa8, 0x43, 0xf2, 0xef, 0x00, 0xe2, 0x6b, 0xf5,
	0x63, 0xf9, 0x1b, 0x73, 0x27, 0x4e, 0x20, 0x22, 0x95, 0xad, 0xf1, 0x2e, 0x19, 0x9c, 0x0d, 0x66,
	0xe3, 0x74, 0x44, 0xea, 0x1b, 0xde, 0x89, 0x53, 0x18, 0x93, 0xca, 0x96, 0x4d, 0xbe, 0x46, 0x97,
	0xec, 0x33, 0x13, 0x93, 0xfa, 0xc4, 0x58, 0xbc, 0x81, 0x17, 0xa4, 0x32, 0x9d, 0xe7, 0x48, 0xd4,
	0x76, 0x1e, 0x30, 0x3f, 0x21, 0xb5, 0x08, 0x47, 0x5e, 0x42, 0x98, 0xd7, 0xe8, 0x5a, 0xc9, 0x30,
	0x48, 0xae, 0xc3, 0x91, 0x78, 0x0d, 0x13, 0x52, 0x19, 0x9a, 0x62, 0x6b, 0x2b, 0xe3, 0x92, 0x11,
	0x2b, 0x80, 0xd4, 0x17, 0x7f, 0xe2, 0x3d, 0xd4, 0x58, 0x56, 0xd6, 0x24, 0x51, 0xf0, 0x90, 0x32,
	0x96, 0xa7, 0x30, 0xfa, 0xba, 0xd1, 0x25, 0x0a, 0x01, 0x43, 0xa3, 0x37, 0xe8, 0xed, 0x73, 0x2d,
	0x15, 0x00, 0x93, 0x74, 0x55, 0x91, 0x13, 0xef, 0x20, 0xaa, 0x18, 0x25, 0x83, 0xb3, 0x83, 0xd9,
	0xe4, 0xfc, 0x68, 0xee, 0x63, 0x61, 0x4d, 0xea, 0x49, 0xb9, 0x84, 0xf8, 0x46, 0x97, 0xdd, 0xd0,
	0xf7, 0x30, 0xb6, 0xb7, 0x45, 0xc6, 0x0c, 0x4f, 0xfe, 0xaf, 0x2b, 0xb6, 0xb7, 0x45, 0xaf, 0x35,
	0xb8, 0xf3, 0xda, 0xfd, 0x67, 0xb5, 0x06, 0x77, 0x5c, 0xc9, 0x0b, 0x38, 0x0a, 0x3b, 0x3a, 0x6f,
	0xb3, 0x27, 0xde, 0x8e, 0x43, 0x67, 0x90, 0xf5, 0xf6, 0xfe, 0xc0, 0xf1, 0x8d, 0x2e, 0x17, 0xa6,
	0xf8, 0xd9, 0xd0, 0xca, 0x7f, 0xbc, 0x8f, 0x00, 0x4e, 0x97, 0x59, 0x3f, 0xa1, 0xdd, 0x7d, 0xf2,
	0x74, 0x02, 0x2f, 0x4a, 0xc7, 0x2e, 0x40, 0xa1, 0x60, 0xa2, 0x1b, 0xb7, 0xca, 0x72, 0x6b, 0x7e,
	0x55, 0xa5, 0xb7, 0x2c, 0x42, 0xdb, 0xa2, 0x71, 0xab, 0xcf, 0xcc, 0xa4, 0xa0, 0xfb, 0x5a, 0x5e,
	0x02, 0xdc, 0x33, 0x62, 0x0a, 0x71, 0x43, 0x58, 0x3f, 0x08, 0xbe, 0xc7, 0x2d, 0xb7, 0xd5, 0x44,
	0x3b, 0x5b, 0x17, 0xe1, 0xe6, 0x04, 0x2c, 0xdf, 0xc2, 0xe1, 0x77, 0x24, 0x6a, 0x63, 0x4b, 0xe0,
	0x70, 0xd3, 0x95, 0x7e, 0x42, 0x80, 0xe7, 0x04, 0xd1, 0x25, 0x7b, 0x11, 0x73, 0x18, 0x5e, 0x59,
	0x5d, 0x88, 0x3e, 0x95, 0x70, 0x6d, 0xa7, 0xe2, 0x51, 0xc2, 0xfc, 0x8a, 0x72, 0x4f, 0x5c, 0x00,
	0xdc, 0x67, 0x24, 0x92, 0x07, 0x49, 0x3c, 0xca, 0x6d, 0xfa, 0x32, 0x30, 0xde, 0x8c, 0xdc, 0x5b,
	0x46, 0xfc, 0x8f, 0xa8, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x69, 0x59, 0x8c, 0xd9, 0x3a, 0x03,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DockerClient is the client API for Docker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DockerClient interface {
	Load(ctx context.Context, in *S3Object, opts ...grpc.CallOption) (*ImagesList, error)
	TagAndPush(ctx context.Context, in *TagAndPushObject, opts ...grpc.CallOption) (*Message, error)
}

type dockerClient struct {
	cc *grpc.ClientConn
}

func NewDockerClient(cc *grpc.ClientConn) DockerClient {
	return &dockerClient{cc}
}

func (c *dockerClient) Load(ctx context.Context, in *S3Object, opts ...grpc.CallOption) (*ImagesList, error) {
	out := new(ImagesList)
	err := c.cc.Invoke(ctx, "/docker.Docker/Load", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerClient) TagAndPush(ctx context.Context, in *TagAndPushObject, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/docker.Docker/TagAndPush", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DockerServer is the server API for Docker service.
type DockerServer interface {
	Load(context.Context, *S3Object) (*ImagesList, error)
	TagAndPush(context.Context, *TagAndPushObject) (*Message, error)
}

// UnimplementedDockerServer can be embedded to have forward compatible implementations.
type UnimplementedDockerServer struct {
}

func (*UnimplementedDockerServer) Load(ctx context.Context, req *S3Object) (*ImagesList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Load not implemented")
}
func (*UnimplementedDockerServer) TagAndPush(ctx context.Context, req *TagAndPushObject) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TagAndPush not implemented")
}

func RegisterDockerServer(s *grpc.Server, srv DockerServer) {
	s.RegisterService(&_Docker_serviceDesc, srv)
}

func _Docker_Load_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(S3Object)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerServer).Load(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/docker.Docker/Load",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerServer).Load(ctx, req.(*S3Object))
	}
	return interceptor(ctx, in, info, handler)
}

func _Docker_TagAndPush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TagAndPushObject)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerServer).TagAndPush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/docker.Docker/TagAndPush",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerServer).TagAndPush(ctx, req.(*TagAndPushObject))
	}
	return interceptor(ctx, in, info, handler)
}

var _Docker_serviceDesc = grpc.ServiceDesc{
	ServiceName: "docker.Docker",
	HandlerType: (*DockerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Load",
			Handler:    _Docker_Load_Handler,
		},
		{
			MethodName: "TagAndPush",
			Handler:    _Docker_TagAndPush_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "docker/docker.proto",
}
